// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXa_kWXnKs4ziRkJ5w0GMYz5RBuByqm7g',
    appId: '1:355892094147:web:caef4f4e5ac1d76e232e76',
    messagingSenderId: '355892094147',
    projectId: 'flutter-firebase-47374',
    authDomain: 'flutter-firebase-47374.firebaseapp.com',
    storageBucket: 'flutter-firebase-47374.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfpwtf53k_f8JeOpFbMIaRps5Pcyvs19c',
    appId: '1:355892094147:android:b0d28f17500231ec232e76',
    messagingSenderId: '355892094147',
    projectId: 'flutter-firebase-47374',
    storageBucket: 'flutter-firebase-47374.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-esFSKiN97lDUpnG6uLiZnc4RMU8nUYQ',
    appId: '1:355892094147:ios:bb1f9bc2487f4594232e76',
    messagingSenderId: '355892094147',
    projectId: 'flutter-firebase-47374',
    storageBucket: 'flutter-firebase-47374.appspot.com',
    iosBundleId: 'com.example.demoauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-esFSKiN97lDUpnG6uLiZnc4RMU8nUYQ',
    appId: '1:355892094147:ios:bb1f9bc2487f4594232e76',
    messagingSenderId: '355892094147',
    projectId: 'flutter-firebase-47374',
    storageBucket: 'flutter-firebase-47374.appspot.com',
    iosBundleId: 'com.example.demoauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXa_kWXnKs4ziRkJ5w0GMYz5RBuByqm7g',
    appId: '1:355892094147:web:ad3896183353cf5b232e76',
    messagingSenderId: '355892094147',
    projectId: 'flutter-firebase-47374',
    authDomain: 'flutter-firebase-47374.firebaseapp.com',
    storageBucket: 'flutter-firebase-47374.appspot.com',
  );
}
